export default {
	FETCH_WEATHER: 'FETCH_WEATHER',
	REMOVE_CITY: 'REMOVE_CITY',
	EDIT_CITY: 'EDIT_CITY',
	START_LOADING: '_START_LOADING',
	FINISH_LOADING: '_FINISH_LOADING',
	ERROR_LOADING: '_ERROR_LOADING',
}
